### ISSUE TITLE
How does Ego support clone()?

### ISSUE THREAD

**Issue by ncppd** [edgelesssys/ego#147]
Hello and thanks for you effort in this project! I am trying to understand how do you support the clone() system call that native go application perform during startup. 

Also do you use the edge8r library? Is it feasible/easy to include more system calls in your design?

**Comment by thomasten** [comment]
Hi,
The ego-go compiler enforces cgo. When cgo is enabled, Go will use pthread_create instead of clone.

Yes, EGo uses edger8r (from Open Enclave) internally. This is part of the underlying Edgeless RT. EGo's [design](https://docs.edgeless.systems/ego/#/knowledge/model) doesn't provide for the user to add syscalls or ocalls, but one can add them to Edgeless RT. We do this every now and then. We'd also accept contributions if they are generic and helpful for EGo in general.
