### ISSUE TITLE
get seal key by keyinfo only? or must having singer key and keyinfo?

### ISSUE THREAD

**Issue by xichan-ms** [edgelesssys/ego#170]
as the title, I have a question about function GetSealKey.

(1) if I use product key to seal data, can anyone retrieve the seal key by keyinfo only? and no need signer key (same signer to sign the retrieve code)

(2) is there any advice to save the keyinfo? I saw another issue https://github.com/edgelesssys/ego/issues/166, you said no need extra protection, if question 1 is yes, retrieve only needs keyinfo, it's kind of dangerous, which means seal key is equal to keyinfo, right?

![image](https://user-images.githubusercontent.com/26354131/190946782-50f888a1-9b12-497e-bd4e-8da419030c7a.png)

**Comment by thomasten** [comment]
(1) No, keyinfo just contains the security version of the platform and the enclave, and some other non-secret attributes. keyinfo is required to still get the same key if either the platform or the enclave has been updated with security patches. But to get the key, you need (a) the same CPU, and (b) the same enclave (for GetUniqueSealKey) or an enclave with the same ProductID signed by the same signer key (for GetProductSealKey).

(2) Because of (1), keyinfo doesn't need to be specially handled. If it has been manipulated, GetSealKey will either fail or return a wrong key. So the effect is the same as if the sealed data would have been manipulated.

**Comment by xichan-ms** [comment]
ok, thanks a lot
