### ISSUE TITLE
if program complied by ego can run in well performance on non SGX env

### ISSUE THREAD

**Issue by onexie** [edgelesssys/ego#225]
Hi，sometimes I may need to directly run the ego compiled program in a non SGX environment, so I would like to know："If the program compiled by ego runs in OE_SIMULATION=1 mode, how much impact will it have on performance compared to the program compiled by the native go compiler?"

**Comment by thomasten** [comment]
Hi,
It depends. If the program is compute-intensive, the overhead will be small. If it is I/O-intensive, the overhead will be greater because the way ocalls are simulated involves syscalls. You would need to measure the actual program to get an answer on this.

You can also invoke the compiled program directly without EGo. It will then run with performance close to the native go compiler. However, some features of the EGo API, which are simulated by `ego run` with OE_SIMULATION=1, won't work.

**Comment by onexie** [comment]
Than you,I got it
